import ImagekitProvider from "@/providers/imagekit-provider"
import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ImagekitProvider>
          {children}
        </ImagekitProvider>
      </body>
    </html>
  )
}
